import json
from typing import Any

from app.handlers.exceptions import AIException
from app.schemas.ats import ATSAnalysis


def _clean_json_response(response: str) -> str:
    """
    Remove Markdown code fences from AI responses.
    """
    response = response.strip()

    if response.startswith("```json"):
        response = response.replace("```json", "", 1)

    if response.startswith("```"):
        response = response.replace("```", "", 1)

    if response.endswith("```"):
        response = response[:-3]

    return response.strip()


def parse_response(response: str) -> ATSAnalysis:
    """
    Parse ATS analysis response into an ATSAnalysis schema.
    """
    try:
        cleaned = _clean_json_response(response)
        data = json.loads(cleaned)
        return ATSAnalysis(**data)

    except json.JSONDecodeError:
        raise AIException(
            "Invalid JSON returned by AI.",
            error_code="AI_INVALID_JSON",
        )

    except Exception:
        raise AIException(
            "Failed to parse ATS analysis.",
            error_code="AI_PARSE_ERROR",
        )


def parse_interview_questions(
    response: str,
) -> dict[str, Any]:
    """
    Parse interview questions generated by AI.
    """
    try:
        cleaned = _clean_json_response(response)
        return json.loads(cleaned)

    except json.JSONDecodeError:
        raise AIException(
            "Invalid JSON returned by AI.",
            error_code="AI_INVALID_JSON",
        )


def parse_resume_improvement(
    response: str,
) -> dict[str, Any]:
    """
    Parse resume improvement suggestions.
    """
    try:
        cleaned = _clean_json_response(response)
        return json.loads(cleaned)

    except json.JSONDecodeError:
        raise AIException(
            "Invalid JSON returned by AI.",
            error_code="AI_INVALID_JSON",
        )