import json
import re
from typing import Any

from app.core.logger import logger
from app.handlers.exceptions import AIException
from app.schemas.ats import ATSAnalysis


def _clean_json_response(response: str) -> str:
    """
    Remove Markdown code fences and reasoning tags from AI responses.
    """
    if not response or not isinstance(response, str):
        return ""

    response = response.strip()

    # Remove reasoning/thinking blocks if model generates them
    response = re.sub(r"<think>.*?</think>", "", response, flags=re.DOTALL).strip()

    if response.startswith("```json"):
        response = response.replace("```json", "", 1)

    if response.startswith("```"):
        response = response.replace("```", "", 1)

    if response.endswith("```"):
        response = response[:-3]

    return response.strip()


def parse_response(response: str) -> ATSAnalysis:
    """
    Parse ATS analysis response into an ATSAnalysis schema.
    """
    try:
        cleaned = _clean_json_response(response)
        data = json.loads(cleaned)

        raw_score = data.get("ats_score", 0)
        try:
            score = int(round(float(raw_score)))
        except (ValueError, TypeError):
            score = 0
        score = max(0, min(100, score))

        def _to_list(val: Any) -> list[str]:
            if isinstance(val, list):
                return [str(x) for x in val if x]
            if isinstance(val, str) and val.strip():
                return [val.strip()]
            return []

        analysis_dict = {
            "ats_score": score,
            "summary": str(data.get("summary", "")).strip() or "Resume analysis completed.",
            "strengths": _to_list(data.get("strengths")),
            "weaknesses": _to_list(data.get("weaknesses")),
            "missing_skills": _to_list(data.get("missing_skills")),
            "grammar": str(data.get("grammar", "")).strip() or "Grammar and tone are acceptable.",
            "formatting": str(data.get("formatting", "")).strip() or "Standard formatting.",
            "recommendations": _to_list(data.get("recommendations")),
        }

        return ATSAnalysis(**analysis_dict)

    except json.JSONDecodeError as exc:
        logger.warning("JSON decode failure in ATS response: %s", exc)
        raise AIException(
            "Unable to parse AI ATS analysis. Please try again.",
            error_code="AI_INVALID_JSON",
        )

    except Exception as exc:
        logger.warning("Unexpected ATS parsing failure: %s", exc)
        raise AIException(
            message="Unable to process ATS analysis. Please try again.",
            error_code="AI_PARSE_ERROR",
        )


def parse_interview_questions(
    response: str,
) -> dict[str, Any]:
    """
    Parse interview questions generated by AI.
    """
    try:
        cleaned = _clean_json_response(response)
        data = json.loads(cleaned)

        # Support both shorthand and alternative key naming
        tech = data.get("technical") or data.get("technical_questions") or []
        beh = data.get("behavioral") or data.get("behavioral_questions") or []
        hr = data.get("hr") or data.get("hr_questions") or []
        tips = data.get("tips") or data.get("interview_tips") or []

        def _ensure_list(items: Any) -> list:
            if isinstance(items, list):
                return items
            if isinstance(items, (dict, str)):
                return [items]
            return []

        return {
            "technical": _ensure_list(tech),
            "behavioral": _ensure_list(beh),
            "hr": _ensure_list(hr),
            "tips": _ensure_list(tips),
        }

    except json.JSONDecodeError as exc:
        logger.warning("JSON decode failure in interview questions: %s", exc)
        raise AIException(
            "Unable to parse generated interview questions. Please try again.",
            error_code="AI_INVALID_JSON",
        )
    except Exception as exc:
        logger.warning("Unexpected interview questions parse error: %s", exc)
        raise AIException(
            "Unable to process interview questions. Please try again.",
            error_code="AI_PARSE_ERROR",
        )


def parse_interview_evaluation(response: str) -> dict:
    """
    Parse interview evaluation response from AI.
    Expected JSON:

    {
        "score": 8,
        "strengths": ["..."],
        "improvements": ["..."],
        "ideal_answer": "..."
    }
    """
    try:
        cleaned = _clean_json_response(response)
        data = json.loads(cleaned)

        raw_score = data.get("score")
        score = 7
        if isinstance(raw_score, (int, float)):
            score = int(round(raw_score))
        elif isinstance(raw_score, str):
            match = re.search(r"\d+", raw_score)
            if match:
                score = int(match.group(0))

        # Clamp score between 0 and 10
        score = max(0, min(10, score))

        strengths = data.get("strengths") or data.get("strengths_list") or []
        if isinstance(strengths, str):
            strengths = [strengths]

        improvements = data.get("improvements") or data.get("improvement_areas") or []
        if isinstance(improvements, str):
            improvements = [improvements]

        ideal_answer = (
            data.get("ideal_answer")
            or data.get("improved_answer")
            or data.get("sample_answer")
            or ""
        )

        return {
            "score": score,
            "strengths": strengths if isinstance(strengths, list) else [],
            "improvements": improvements if isinstance(improvements, list) else [],
            "ideal_answer": str(ideal_answer),
        }

    except json.JSONDecodeError as exc:
        logger.warning("JSON decode failure in interview evaluation: %s", exc)
        raise AIException(
            "Unable to parse AI interview evaluation. Please try again.",
            error_code="AI_INVALID_JSON",
        )
    except Exception as exc:
        logger.warning("Unexpected interview evaluation parse error: %s", exc)
        raise AIException(
            "Unable to process interview evaluation. Please try again.",
            error_code="AI_PARSE_ERROR",
        )


def parse_resume_improvement(
    response: str,
) -> dict[str, Any]:
    """
    Parse resume improvement suggestions.
    """
    try:
        cleaned = _clean_json_response(response)
        data = json.loads(cleaned)
        if not isinstance(data, dict):
            raise AIException("Invalid response structure from AI.")
        return data

    except json.JSONDecodeError as exc:
        logger.warning("JSON decode failure in resume improvement: %s", exc)
        raise AIException(
            "Unable to parse resume improvement suggestions. Please try again.",
            error_code="AI_INVALID_JSON",
        )
    except Exception as exc:
        logger.warning("Unexpected resume improvement parse error: %s", exc)
        raise AIException(
            "Unable to process resume improvements. Please try again.",
            error_code="AI_PARSE_ERROR",
        )