import json
import re
from typing import Any

from app.handlers.exceptions import AIException
from app.schemas.ats import ATSAnalysis


def _clean_json_response(response: str) -> str:
    """
    Remove Markdown code fences and reasoning tags from AI responses.
    """
    response = response.strip()

    # Remove reasoning/thinking blocks if model generates them
    response = re.sub(r"<think>.*?</think>", "", response, flags=re.DOTALL).strip()

    if response.startswith("```json"):
        response = response.replace("```json", "", 1)

    if response.startswith("```"):
        response = response.replace("```", "", 1)

    if response.endswith("```"):
        response = response[:-3]

    return response.strip()


def parse_response(response: str) -> ATSAnalysis:
    """
    Parse ATS analysis response into an ATSAnalysis schema.
    """
    try:
        cleaned = _clean_json_response(response)
        data = json.loads(cleaned)
        return ATSAnalysis(**data)

    except json.JSONDecodeError:
        raise AIException(
            "Invalid JSON returned by AI.",
            error_code="AI_INVALID_JSON",
        )

    except Exception as e:
        raise AIException(
            message=f"Failed to parse ATS analysis: {str(e)}",
            error_code="AI_PARSE_ERROR",
        )


def parse_interview_questions(
    response: str,
) -> dict[str, Any]:
    """
    Parse interview questions generated by AI.
    """
    try:
        cleaned = _clean_json_response(response)
        data = json.loads(cleaned)
        
        # Support both shorthand and alternative key naming
        tech = data.get("technical") or data.get("technical_questions") or []
        beh = data.get("behavioral") or data.get("behavioral_questions") or []
        hr = data.get("hr") or data.get("hr_questions") or []
        tips = data.get("tips") or data.get("interview_tips") or []

        return {
            "technical": tech,
            "behavioral": beh,
            "hr": hr,
            "tips": tips,
        }

    except json.JSONDecodeError:
        raise AIException(
            "Invalid JSON returned by AI.",
            error_code="AI_INVALID_JSON",
        )


def parse_interview_evaluation(response: str) -> dict:
    """
    Parse interview evaluation response from AI.
    Expected JSON:

    {
        "score": 8,
        "strengths": ["..."],
        "improvements": ["..."],
        "ideal_answer": "..."
    }
    """
    try:
        cleaned = _clean_json_response(response)
        data = json.loads(cleaned)

        raw_score = data.get("score")
        score = 8
        if isinstance(raw_score, (int, float)):
            score = int(round(raw_score))
        elif isinstance(raw_score, str):
            match = re.search(r"\d+", raw_score)
            if match:
                score = int(match.group(0))

        # Clamp score between 0 and 10
        score = max(0, min(10, score))

        strengths = data.get("strengths") or data.get("strengths_list") or []
        if isinstance(strengths, str):
            strengths = [strengths]

        improvements = data.get("improvements") or data.get("improvement_areas") or []
        if isinstance(improvements, str):
            improvements = [improvements]

        ideal_answer = (
            data.get("ideal_answer")
            or data.get("improved_answer")
            or data.get("sample_answer")
            or ""
        )

        return {
            "score": score,
            "strengths": strengths,
            "improvements": improvements,
            "ideal_answer": ideal_answer,
        }

    except json.JSONDecodeError:
        raise AIException(
            "Invalid JSON returned by AI evaluation.",
            error_code="AI_INVALID_JSON",
        )
    except Exception as e:
        raise AIException(
            f"Failed to parse interview evaluation: {str(e)}",
            error_code="AI_PARSE_ERROR",
        )
    
def parse_resume_improvement(
    response: str,
) -> dict[str, Any]:
    """
    Parse resume improvement suggestions.
    """
    try:
        cleaned = _clean_json_response(response)
        return json.loads(cleaned)

    except json.JSONDecodeError:
        raise AIException(
            "Invalid JSON returned by AI.",
            error_code="AI_INVALID_JSON",
        )