import { FileText, Sparkles, Briefcase, Brain } from "lucide-react";

const features = [
  {
    icon: FileText,
    title: "ATS Resume Analysis",
    description:
      "Analyze your resume against any job description with an AI-powered ATS score.",
  },
  {
    icon: Sparkles,
    title: "Resume Optimization",
    description:
      "Improve your resume using AI-generated suggestions tailored to each company.",
  },
  {
    icon: Briefcase,
    title: "Cover Letter Generator",
    description:
      "Generate personalized cover letters in seconds using your resume and the job description.",
  },
  {
    icon: Brain,
    title: "Interview Preparation",
    description:
      "Receive company-specific HR and technical interview questions generated by AI.",
  },
];

export default function Features() {
  return (
    <section className="mx-auto max-w-7xl px-6 py-24">
      <h2 className="mb-14 text-center text-4xl font-bold">
        Everything You Need to Get Hired
      </h2>

      <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
        {features.map((feature) => (
          <div
            key={feature.title}
            className="rounded-2xl border border-slate-800 bg-slate-900 p-6 transition hover:border-cyan-500"
          >
            <feature.icon className="mb-5 h-10 w-10 text-cyan-400" />

            <h3 className="mb-3 text-xl font-semibold">
              {feature.title}
            </h3>

            <p className="text-slate-400">
              {feature.description}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
}